name: Java CI Test
env:
  junit_platform_version: '1.9.3'
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:

  test:
    runs-on: ${{ matrix.os }}
    env:
      LANG: en_US.UTF-8
    strategy:
      fail-fast: false
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [11, 17, 21, 22]
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Java ${{ matrix.java }} on ${{ matrix.os }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 256

      - name: Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ~/.ivy2/cache/
            ~/work/josm/josm/tools/
          key: ${{ runner.os }}-ivy2-${{ hashFiles('build.xml', 'ivy.xml', 'tools/ivy.xml') }}

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Install Ant
        uses: JOSM/JOSMPluginAction/actions/setup-ant@e3712b87467296a79a78c07ae0017611a153dad4 # v2.0.7

      - name: Test with Ant
        run: |
          ANT="ant -DnoJavaFX=true test-unit-hardfail"
          $ANT -Dtest.headless=true

      - name: Dump errors if failed
        if: ${{ failure() }}
        run: "grep -L ', Failures: 0, Skipped: ' test/report/*.txt | xargs cat"

      - name: Upload Ant reports
        if: ${{ always() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: Ant reports for JOSM ${{ needs.createrelease.outputs.josm_revision }} on java ${{ matrix.java }} on ${{ matrix.os }}
          path: |
            test/report/*.txt
            test/report/TEST*.xml
            hs_err*

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: test
    runs-on: ubuntu-latest
    # the test job might be skipped, we don't need to run this job then
    if: success() || failure()

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: Download Artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          path: artifacts

      - name: Publish Test Report with action-junit-report
        if: ${{ always() }}
        uses: mikepenz/action-junit-report@db71d41eb79864e25ab0337e395c352e84523afe # v4.3.1
        with:
          report_paths: 'artifacts/**/*.xml'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Test Report with publish-unit-test-result-action
        uses: step-security/publish-unit-test-result-action@7dff603bf17ef13dee847147bef8d7cd1728b566 # v2.22.0
        with:
          files: 'artifacts/**/*.xml'
