name: "Spotbugs"

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

permissions:
  contents: read

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
      with:
        egress-policy: audit

    - name: Checkout repository
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      with:
          fetch-depth: 256

    - name: Cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          ~/.ivy2/cache/
          ~/work/josm/josm/tools/
        key: ${{ runner.os }}-ivy2-${{ hashFiles('build.xml', 'ivy.xml', 'tools/ivy.xml') }}

    - name: Run Spotbugs with Ant
      run: |
        ant spotbugs

    - name: Upload report
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        path: spotbugs-josm.xml

    # Disable step, always failing with error message
    # TypeError: Cannot read property 'sourcepath' of undefined
    # see https://github.com/jwgmeligmeyling/spotbugs-github-action/issues/15
    #- uses: jwgmeligmeyling/spotbugs-github-action@master
    #  with:
    #    path: '**/spotbugs-josm.xml'
